<?php echo $this->doctype() ?>

<html>
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <?php echo $this->placeholder('html5js') ?>
    <![endif]-->

    <?php echo $this->headScript() ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <!-- Le fav and touch icons -->
    <?php echo $this->placeholder('favicon') ?>

  </head>

  <body>

    <div class="container">
      <?php echo $this->content; ?>

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>
